"""
Tinkoff Acquiring Service for subscription payment processing
Based on Tinkoff Acquiring API integration playbook
"""
import hashlib
import hmac
import httpx
import logging
import os
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class TinkoffAcquiringService:
    """Service for interacting with Tinkoff Acquiring API"""
    
    def __init__(self):
        self.terminal_key = os.getenv("TINKOFF_TERMINAL_KEY", "")
        self.password = os.getenv("TINKOFF_TERMINAL_PASSWORD", "")
        self.base_url = os.getenv("TINKOFF_BASE_URL", "https://securepay.tinkoff.ru/v2")
        self.debug_mode = os.getenv("TINKOFF_DEBUG_MODE", "true").lower() == "true"
        self.timeout = 30
    
    def _generate_token(self, data: Dict[str, Any]) -> str:
        """
        Generate HMAC-SHA256 token for request authentication.
        
        Token is generated by concatenating all request values in 
        alphabetical key order, appending the password, hashing with SHA256,
        then converting to uppercase hexadecimal format.
        """
        # Sort keys alphabetically and concatenate values
        sorted_keys = sorted(data.keys())
        concatenated = "".join(str(data[key]) for key in sorted_keys)
        
        # Append password and hash with terminal password
        concatenated_with_password = concatenated + self.password
        
        # Generate HMAC-SHA256 signature
        signature = hmac.new(
            self.password.encode(),
            concatenated_with_password.encode(),
            hashlib.sha256
        ).hexdigest().upper()
        
        return signature
    
    def _prepare_request(self, method: str, data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Prepare request with token and required fields.
        
        Adds TerminalKey to request data and generates authentication token.
        """
        # Add terminal key to request
        request_data = {
            "TerminalKey": self.terminal_key,
            **data
        }
        
        # Generate token
        token = self._generate_token(request_data)
        request_data["Token"] = token
        
        return request_data
    
    async def init_payment(
        self, 
        amount: int,  # Amount in kopecks (1 RUB = 100 kopecks)
        order_id: str,
        customer_key: str,
        description: str,
        email: str,
        recurrent: bool = False
    ) -> Dict[str, Any]:
        """
        Initialize a payment transaction.
        
        Args:
            amount: Payment amount in kopecks
            order_id: Unique order identifier in your system
            customer_key: Customer identifier for recurring payments
            description: Payment description for customer
            email: Customer email for receipt
            recurrent: Enable recurring payment capability
            
        Returns:
            Response containing PaymentId and PaymentURL
        """
        payload = {
            "Amount": amount,
            "OrderId": order_id,
            "Description": description,
            "Language": "ru",
            "Email": email,
        }
        
        # Add recurring payment parameters if enabled
        if recurrent:
            payload["Recurrent"] = "Y"
            payload["CustomerKey"] = customer_key
        
        # Prepare request with authentication
        request_data = self._prepare_request("Init", payload)
        
        # Send to Tinkoff API
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(
                    f"{self.base_url}/Init",
                    json=request_data
                )
                return response.json()
            except Exception as e:
                logger.error(f"Failed to initialize payment: {str(e)}")
                return {"Success": False, "ErrorCode": "NETWORK_ERROR", "Message": str(e)}
    
    async def get_payment_state(self, payment_id: str) -> Dict[str, Any]:
        """
        Retrieve current payment status from Tinkoff.
        
        Args:
            payment_id: Tinkoff payment identifier
            
        Returns:
            Payment status and details
        """
        payload = {"PaymentId": payment_id}
        request_data = self._prepare_request("GetState", payload)
        
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(
                    f"{self.base_url}/GetState",
                    json=request_data
                )
                return response.json()
            except Exception as e:
                logger.error(f"Failed to get payment state: {str(e)}")
                return {"Success": False, "ErrorCode": "NETWORK_ERROR", "Message": str(e)}
    
    async def charge_recurring(
        self,
        payment_id: str,
        rebill_id: str,
        amount: int
    ) -> Dict[str, Any]:
        """
        Charge customer using saved card for recurring payment.
        
        Args:
            payment_id: Initial payment ID from first transaction
            rebill_id: Rebill ID from first payment response
            amount: Amount to charge in kopecks
            
        Returns:
            Charge operation response
        """
        payload = {
            "PaymentId": payment_id,
            "RebillId": rebill_id,
            "Amount": amount,
        }
        request_data = self._prepare_request("Charge", payload)
        
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(
                    f"{self.base_url}/Charge",
                    json=request_data
                )
                return response.json()
            except Exception as e:
                logger.error(f"Failed to charge recurring payment: {str(e)}")
                return {"Success": False, "ErrorCode": "NETWORK_ERROR", "Message": str(e)}
    
    async def cancel_payment(self, payment_id: str) -> Dict[str, Any]:
        """
        Cancel an authorized but not confirmed payment.
        
        Args:
            payment_id: Tinkoff payment identifier
            
        Returns:
            Cancellation response
        """
        payload = {"PaymentId": payment_id}
        request_data = self._prepare_request("Cancel", payload)
        
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.post(
                    f"{self.base_url}/Cancel",
                    json=request_data
                )
                return response.json()
            except Exception as e:
                logger.error(f"Failed to cancel payment: {str(e)}")
                return {"Success": False, "ErrorCode": "NETWORK_ERROR", "Message": str(e)}
    
    def validate_webhook_signature(
        self, 
        webhook_data: Dict[str, Any], 
        provided_signature: str
    ) -> bool:
        """
        Validate webhook signature to ensure authenticity.
        
        Webhooks from Tinkoff include a Token field that proves the message
        originated from Tinkoff and has not been modified. This validation
        prevents processing of fake or tampered payment notifications.
        
        Args:
            webhook_data: Complete webhook payload
            provided_signature: Token field from webhook
            
        Returns:
            True if signature is valid, False otherwise
        """
        # Create copy without Token for signature calculation
        data_for_signing = {k: v for k, v in webhook_data.items() if k != "Token"}
        
        # Sort keys alphabetically and concatenate values
        sorted_keys = sorted(data_for_signing.keys())
        concatenated = "".join(str(data_for_signing[key]) for key in sorted_keys)
        
        # Append password
        concatenated_with_password = concatenated + self.password
        
        # Calculate expected token
        expected_token = hmac.new(
            self.password.encode(),
            concatenated_with_password.encode(),
            hashlib.sha256
        ).hexdigest().upper()
        
        # Compare tokens - use constant-time comparison to prevent timing attacks
        return hmac.compare_digest(expected_token, provided_signature.upper())
